spring:
  #port: 8083
 # security:
  #  user:
   #   name: tareg
    #  password: 123456

  application:
    name: log-in-server

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microserviceapi
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#external-url:
 # flight-amenities: http://localhost:3000/amenities

server:
  port: 8083 #set your portg
  servlet:
    context-path: /auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost









