server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: userModules
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: deparmentModules
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
